import sys
from collections import OrderedDict

mappings = OrderedDict([
('medicine', 'medicine'),
('biology', 'biology'),
('physics', 'physics'),
('chemistry', 'chemistry'),
('pathology', 'medicine'),
('surgery', 'medicine'),
('genetics', 'biology'),
('immunology', 'biology'),
('biochemistry', 'chemistry'),
('computer science', 'computer science'),
('psychology', 'psychology'),
('quantum mechanics', 'physics'),
('engineering', 'engineering'),
('organic chemistry', 'chemistry'),
('endocrinology', 'medicine'),
('diabetes mellitus', 'medicine'),
('anatomy', 'biology'),
('materials science', 'materials science'),
('ecology', 'environmental science'),
('mathematics', 'mathematics'),
('optics', 'physics'),
('botany', 'environmental science'),
('statistics', 'mathematics'),
('molecular biology', 'biology'),
('analytical chemistry', 'chemistry'),
('stereochemistry', 'chemistry'),
('social psychology', 'psychology'),
('bioinformatics', 'biology'),
('nanotechnology', 'physics'),
('physical therapy', 'medicine'),
('psychiatry', 'psychology'),
('electronic engineering', 'engineering'),
('ceramic materials', 'materials science'),
('developmental psychology', 'psychology'),
('economics', 'social science'),
('mineralogy', 'environmental science'),
('virology', 'biology'),
('nuclear magnetic resonance', 'physics'),
('chromatography', 'chemistry'),
('anesthesia', 'medicine'),
('neuroscience', 'biology'),
('inorganic chemistry', 'chemistry'),
('forensic engineering', 'engineering'),
('mathematical optimization', 'mathematics'),
('radiology', 'medicine'),
('geology', 'environmental science'),
('microbiology', 'biology'),
('telecommunications', 'engineering'),
('intensive care medicine', 'medicine'),
('metallurgy', 'materials science'),
('condensed matter physics', 'physics'),
('gynecology', 'medicine'),
('crystallography', 'physics'),
('biotechnology', 'biology'),
('management', 'business'),
('composite material', 'materials science'),
('data mining', 'computer science'),
('communication', 'business'),
('pediatrics', 'medicine'),
('operations management', 'business'),
('thermodynamics', 'physics'),
('machine learning', 'computer science'),
('pharmacology', 'medicine'),
('atomic physics', 'physics'),
('electrical engineering', 'engineering'),
('sociology', 'social science'),
('control engineering', 'engineering'),
('meteorology', 'environmental science'),
('computer vision', 'computer science'),
('hydrology', 'environmental science'),
('control theory', 'engineering'),
('nursing', 'medicine'),
('clinical psychology', 'psychology'),
('artificial intelligence', 'computer science'),
('polymer chemistry', 'chemistry'),
('cardiology', 'medicine'),
('photochemistry', 'chemistry'),
('environmental engineering', 'engineering'),
('medical emergency', 'medicine'),
('enzyme', 'biology'),
('classical mechanics', 'physics'),
('astronomy', 'physics'),
('optoelectronics', 'engineering'),
('real-time computing', 'computer science'),
('alternative medicine', 'medicine'),
('astrophysics', 'physics'),
('pedagogy', 'social science'),
('computer security', 'social science'),
('mathematical analysis', 'computer science'),
('economic growth', 'mathematics'),
('law', 'social science'),
('discrete mathematics', 'social science'),
('text mining', 'mathematics'),
('cell biology', 'computer science'),
('gerontology', 'biology'),
('paleontology', 'biology'),
('medical research', 'medicine'),
('marketing', 'business'),
('agronomy', 'environmental science'),
('combinatorics', 'mathematics'),
('algorithm', 'mathematics'),
('computer network', 'computer science'),
('structural engineering', 'engineering'),
('engineering drawing', 'engineering'),
('theoretical computer science', 'computer science'),
('physical chemistry', 'chemistry'),
('social science', 'social science'),
('world wide web', 'computer science'),
('geotechnical engineering', 'engineering'),
('computational chemistry', 'chemistry'),
('calculus', 'mathematics'),
('econometrics', 'social science'),
('oncology', 'medicine'),
('psychotherapist', 'psychology'),
('mechanical engineering', 'engineering'),
('suicide prevention', 'psychology'),
('injury prevention', 'medicine'),
('public health', 'social science'),
('oceanography', 'environmental science'),
('knowledge management', 'business'),
('risk factor', 'business'),
('nuclear physics', 'physics'),
('epidemiology', 'medicine'),
('geometry', 'mathematics'),
('environmental chemistry', 'chemistry'),
('embedded system', 'computer science'),
('geomorphology', 'environmental science'),
('geography', 'social science'),
('distributed computing', 'computer science'),
('public relations', 'social science'),
('cell culture', 'biology'),
('cancer', 'medicine'),
('computer simulation', 'computer science'),
('dentistry', 'medicine'),
('multimedia', 'humanities'),
('gene expression', 'biology'),
('kinetics', 'physics'),
('toxicology', 'medicine'),
('cancer research', 'medicine'),
('quantum electrodynamics', 'physics'),
('pattern recognition', 'computer science'),
('x-ray crystallography', 'physics'),
('database', 'computer science'),
('operating system', 'computer science'),
('environmental health', 'environmental science'),
('nuclear medicine', 'medicine'),
('magnetic resonance imaging', 'medicine'),
('topology', 'physics'),
('environmental resource management', 'environmental science'),
('economy', 'social science'),
('climatology', 'environmental science'),
('biological engineering', 'engineering'),
('young adult', 'social science'),
('family medicine', 'medicine'),
('speech recognition', 'computer science'),
('apoptosis', 'biology'),
('general surgery', 'medicine'),
('bacteria', 'biology'),
('thin film', 'materials science'),
('fishery', 'environmental science'),
('commerce', 'business'),
('physical medicine and rehabilitation', 'medicine'),
('central nervous system', 'biology'),
('medical physics', 'physics'),
('cognitive psychology', 'psychology'),
('actuarial science', 'mathematics'),
('business', 'business'),
('algebra', 'mathematics'),
('particle physics', 'physics'),
('gene', 'biology'),
('gastroenterology', 'medicine'),
('microstructure', 'materials science'),
('operations research', 'business'),
('finance', 'business'),
('in vitro', 'biology'),
('management science', 'business'),
('environmental protection', 'environmental science'),
('geophysics', 'physics'),
('mass spectrometry', 'chemistry'),
('immunohistochemistry', 'chemistry'),
('mathematical model', 'mathematics'),
('food science', 'chemistry'),
('signal transduction', 'engineering'),
('systems modeling', 'business'),
('crystal structure', 'materials science'),
('advertising', 'business'),
('iron', 'materials science'),
('toxicity', 'biology'),
('agroforestry', 'environmental science'),
('linguistics', 'social science'),
('mutation', 'biology'),
('programming language', 'computer science'),
('veterinary medicine', 'medicine'),
('microeconomics', 'social science'),
('atmospheric sciences', 'environmental science'),
('cognition', 'psychology'),
('parallel computing', 'computer science'),
('magnetic field', 'physics'),
('systems engineering', 'engineering'),
('simulation', 'engineering'),
('bagasse', 'materials science'),
('urology', 'medicine'),
('magnesium', 'materials science'),
('chem', 'chemistry'),
('art', 'humanities'),
('educat', 'social sciences'),
('cell', 'biology'),
('statis', 'mathematics'),
('philosophy', 'humanities'),
('data', 'computer science'),
('robot', 'engineering'),
('history', 'social science'),
('magnet', 'physics'),
('nickel', 'materials science'),
('urology', 'medicine'),
('compute', 'computer science'),
('humanities', 'humanities'),
('demography', 'social science'),
('dermatology', 'medicine'),
('program', 'computer science'),
('sleep', 'psychology'),
('neur', 'psychology'),
('bio', 'biology'),
('heat', 'physics'),
('markov', 'mathematics'),
('laser', 'physics'),
('audiology', 'medicine'),
('optometry', 'medicine'),
('obstetrics', 'medicine'),
('remote sensing', 'physics'),
('acoustics', 'physics'),
('archaeology', 'social science'),
('finite element', 'physics'),
('gender', 'social science'),
('seismology', 'environmental science'),
('animal', 'biology'),
('media', 'humanities'),
('soil', 'environmental science'),
('geo', 'environmental science'),
('image processing', 'computer science'),
('horticulture', 'environmental science'),
('three-dimensional space', 'physics'),
('quality of life', 'psychology'),
('monte carlo method', 'computer science'),
('perception', 'psychology'),
('china', 'social science'),
('physiology', 'medicine'),
('anti-ssa/ro autoantibodies', 'medicine'),
('polymorphism', 'computer science'),
('key distribution in wireless sensor networks', 'computer science'),
('memory', 'psychology'),
('sensor', 'computer science'),
('forestry', 'environmental science'),
('vision', 'psychology'),
('scale-space segmentation', 'mathematics'),
('principal component analysis', 'mathematics'),
('literature', 'humanities'),
('stress', 'psychology'),
('image analysis', 'computer science'),
('behavior', 'psychology'),
('time series', 'computer science'),
('crack closure', 'engineering'),
('public administration', 'social science'),
('scanning confocal electron microscopy', 'physics'),
('k-epsilon turbulence model', 'physics'),
('regression analysis', 'mathematics'),
('copper', 'materials science'),
('microstrip antenna', 'engineering'),
('andrology', 'medicine'),
('health care', 'medicine'),
('natural language processing', 'computer science'),
('cluster analysis', 'mathematics'),
('climate change', 'environmental science'),
('retrospective cohort study', 'medicine'),
('ethnology', 'social science'),
('scanning electron microscope', 'physics'),
('health', 'medicine'),
('developing country', 'social science'),
('ultimate tensile strength', 'materials science'),
('protein', 'biology'),
('carbon film', 'materials science'),
('nanocrystalline silicon', 'materials science'),
('risk assessment', 'business'),
('internet privacy', 'computer science'),
('complex network', 'computer science'),
('calcium', 'chemistry'),
('game theory', 'mathematics'),
('ophthalmology', 'medicine'),
('synchronization of chaos', 'mathematics'),
('intellectual disability', 'psychology'),
('signal processing', 'engineering'),
('anxiety', 'psychology'),
('boundary value problem', 'mathematics'),
('interpolation', 'mathematics'),
('autism', 'psychology'),
('seasonality', 'mathematics'),
('human migration', 'social science'),
('epistemology', 'humanities'),
('nitrogen', 'chemistry'),
('arithmetic', 'mathematics'),
('operator theory', 'mathematics'),
('zinc', 'chemistry'),
('raman spectroscopy', 'physics'),
('dynamic priority scheduling', 'mathematics'),
('sensitivity analysis', 'mathematics'),
('fracture toughness', 'materials science'),
('carbon', 'chemistry'),
('routing', 'computer science'),
('blood pressure', 'medicine'),
('sediment', 'environmental science'),
('link-state routing protocol', 'computer science'),
('stochastic process', 'mathematics'),
('multi-swarm optimization', 'mathematics'),
('the internet', 'computer science'),
('fracture', 'materials science'),
('mobile computing', 'computer science'),
('open-channel flow', 'physics'),
('graphene oxide paper', 'materials science'),
('small-angle neutron scattering', 'physics'),
('satisfiability', 'mathematics'),
('redox', 'chemistry'),
('polymerization', 'chemistry'),
('accuracy and precision', 'mathematics'),
('anthropology', 'social science'),
('information retrieval', 'comopter science'),
('inelastic scattering', 'physics'),
('low-pressure area', 'environmental science'),
('support vector machine', 'computer science'),
('nonlinear system', 'mathematics'),
('chip', 'computer science'),
('silicon', 'materials science'),
('noise', 'mathematics'),
('stability', 'physics'),
('distribution', 'mathematics'),
('boundary layer', 'physics'),
('adipose tissue', 'biology'),
('lithium vanadium phosphate battery', 'materials science'),
('ultrasound', 'physics'),
('nanocomposite', 'physics'),
('fracture', 'materials science'),
('mobile computing', 'computer science'),
('open-channel flow', 'physics'),
('graphene oxide paper', 'materials science'),
('small-angle neutron scattering', 'physics'),
('el ni\\xc''\\xb''o', 'environmental science'),
('satisfiability', 'mathematics'),
('redox', 'chemistry'),
('polymerization', 'chemistry'),
('accuracy and precision', 'mathematics'),
('anthropology', 'social science'),
('information retrieval', 'computer science'),
('inelastic scattering', 'physics'),
('low-pressure area', 'environmental science'),
('support vector machine', 'computer science'),
('nonlinear system', 'mathematics'),
('chip', 'computer science'),
('silicon', 'materials science'),
('noise', 'mathematics'),
('stability', 'physics'),
('distribution', 'mathematics'),
('boundary layer', 'physics'),
('adipose tissue', 'biology'),
('lithium vanadium phosphate battery', 'materials science'),
('ultrasound', 'physics'),
('nanocomposite', 'physics'),
('el ni\\xc3\\xb1o', 'environmental science'),
('diesel fuel', 'chemistry'),
('luminous infrared galaxy', 'physics'),
('reactive-ion etching', 'materials science'),
('language', 'social sciences')
])

def do_mapping():
	f = open(sys.argv[1])
	r = f.readline()
	while r:
		r = r.lower()
		if r == 'n\n':
			print('n')
		else:
			found = False
			for key, value in mappings.items():
				if key in r:
					print('y,\'{0}\''.format(value))
					found = True
					break
			if not found:
				print('n')
		r = f.readline()


if __name__ == '__main__':
	do_mapping()

